version: '3'

services:
  app:
    build: '.'
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - TUTOR-VIRTUAL_DATABASE_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
