default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: czdiego
  password: sergtsop

development:
  <<: *default
  database: tutor-virtual_development

test:
  <<: *default
  database: tutor-virtual_test

production:
  <<: *default
  database: tutor-virtual_production